// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

exports.PacketType = {
  "PERSISTENT": 1,
  "BOOTSTRAP_REQUEST": 2,
  "BOOTSTRAP_RESPONSE": 3,
  "CONNECTED": 4,
  "DISCONNECTED": 5,
  "TOPIC_JOIN": 6,
  "TOPIC_LEAVE": 7,
  "USER_DATA": 8,
  "BROADCAST": 9,
  "MESSAGE": 10
}

var Broadcast = exports.Broadcast = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Persistence = exports.Persistence = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Topic = exports.Topic = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var BootstrapPeer = exports.BootstrapPeer = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Bootstrap = exports.Bootstrap = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Subscription = exports.Subscription = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Packet = exports.Packet = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Map_string_Topic = exports.Map_string_Topic = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Map_string_BootstrapPeer = exports.Map_string_BootstrapPeer = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineBroadcast()
definePersistence()
defineTopic()
defineBootstrapPeer()
defineBootstrap()
defineSubscription()
definePacket()
defineMap_string_Topic()
defineMap_string_BootstrapPeer()

function defineBroadcast () {
  Broadcast.encodingLength = encodingLength
  Broadcast.encode = encode
  Broadcast.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.origin)) {
      var len = encodings.bytes.encodingLength(obj.origin)
      length += 1 + len
    }
    if (defined(obj.seq)) {
      var len = encodings.varint.encodingLength(obj.seq)
      length += 1 + len
    }
    if (defined(obj.ttl)) {
      var len = encodings.varint.encodingLength(obj.ttl)
      length += 1 + len
    }
    if (defined(obj.data)) {
      var len = encodings.bytes.encodingLength(obj.data)
      length += 1 + len
    }
    if (defined(obj.nonce)) {
      var len = encodings.bytes.encodingLength(obj.nonce)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.origin)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.origin, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.seq)) {
      buf[offset++] = 16
      encodings.varint.encode(obj.seq, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.ttl)) {
      buf[offset++] = 24
      encodings.varint.encode(obj.ttl, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.data)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.data, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.nonce)) {
      buf[offset++] = 42
      encodings.bytes.encode(obj.nonce, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      origin: null,
      seq: 0,
      ttl: 0,
      data: null,
      nonce: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.origin = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.seq = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 3:
        obj.ttl = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 4:
        obj.data = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 5:
        obj.nonce = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function definePersistence () {
  Persistence.encodingLength = encodingLength
  Persistence.encode = encode
  Persistence.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.ephemeral)) throw new Error("ephemeral is required")
    var len = encodings.bool.encodingLength(obj.ephemeral)
    length += 1 + len
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.ephemeral)) throw new Error("ephemeral is required")
    buf[offset++] = 8
    encodings.bool.encode(obj.ephemeral, buf, offset)
    offset += encodings.bool.encode.bytes
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      ephemeral: false
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.ephemeral = encodings.bool.decode(buf, offset)
        offset += encodings.bool.decode.bytes
        found0 = true
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineTopic () {
  Topic.encodingLength = encodingLength
  Topic.encode = encode
  Topic.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.name)) {
      var len = encodings.string.encodingLength(obj.name)
      length += 1 + len
    }
    if (defined(obj.server)) {
      var len = encodings.bool.encodingLength(obj.server)
      length += 1 + len
    }
    if (defined(obj.client)) {
      var len = encodings.bool.encodingLength(obj.client)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.name)) {
      buf[offset++] = 10
      encodings.string.encode(obj.name, buf, offset)
      offset += encodings.string.encode.bytes
    }
    if (defined(obj.server)) {
      buf[offset++] = 16
      encodings.bool.encode(obj.server, buf, offset)
      offset += encodings.bool.encode.bytes
    }
    if (defined(obj.client)) {
      buf[offset++] = 24
      encodings.bool.encode(obj.client, buf, offset)
      offset += encodings.bool.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      name: "",
      server: false,
      client: false
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.name = encodings.string.decode(buf, offset)
        offset += encodings.string.decode.bytes
        break
        case 2:
        obj.server = encodings.bool.decode(buf, offset)
        offset += encodings.bool.decode.bytes
        break
        case 3:
        obj.client = encodings.bool.decode(buf, offset)
        offset += encodings.bool.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineBootstrapPeer () {
  BootstrapPeer.encodingLength = encodingLength
  BootstrapPeer.encode = encode
  BootstrapPeer.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.connected)) {
      for (var i = 0; i < obj.connected.length; i++) {
        if (!defined(obj.connected[i])) continue
        var len = encodings.bytes.encodingLength(obj.connected[i])
        length += 1 + len
      }
    }
    if (defined(obj.topics)) {
      var tmp = Object.keys(obj.topics)
      for (var i = 0; i < tmp.length; i++) {
        tmp[i] = {key: tmp[i], value: obj.topics[tmp[i]]}
      }
      for (var i = 0; i < tmp.length; i++) {
        if (!defined(tmp[i])) continue
        var len = Map_string_Topic.encodingLength(tmp[i])
        length += varint.encodingLength(len)
        length += 1 + len
      }
    }
    if (defined(obj.userData)) {
      var len = encodings.bytes.encodingLength(obj.userData)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.connected)) {
      for (var i = 0; i < obj.connected.length; i++) {
        if (!defined(obj.connected[i])) continue
        buf[offset++] = 10
        encodings.bytes.encode(obj.connected[i], buf, offset)
        offset += encodings.bytes.encode.bytes
      }
    }
    if (defined(obj.topics)) {
      var tmp = Object.keys(obj.topics)
      for (var i = 0; i < tmp.length; i++) {
        tmp[i] = {key: tmp[i], value: obj.topics[tmp[i]]}
      }
      for (var i = 0; i < tmp.length; i++) {
        if (!defined(tmp[i])) continue
        buf[offset++] = 18
        varint.encode(Map_string_Topic.encodingLength(tmp[i]), buf, offset)
        offset += varint.encode.bytes
        Map_string_Topic.encode(tmp[i], buf, offset)
        offset += Map_string_Topic.encode.bytes
      }
    }
    if (defined(obj.userData)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.userData, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      connected: [],
      topics: {},
      userData: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.connected.push(encodings.bytes.decode(buf, offset))
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tmp = Map_string_Topic.decode(buf, offset, offset + len)
        obj.topics[tmp.key] = tmp.value
        offset += Map_string_Topic.decode.bytes
        break
        case 3:
        obj.userData = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineBootstrap () {
  Bootstrap.encodingLength = encodingLength
  Bootstrap.encode = encode
  Bootstrap.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.bootstrap)) {
      var tmp = Object.keys(obj.bootstrap)
      for (var i = 0; i < tmp.length; i++) {
        tmp[i] = {key: tmp[i], value: obj.bootstrap[tmp[i]]}
      }
      for (var i = 0; i < tmp.length; i++) {
        if (!defined(tmp[i])) continue
        var len = Map_string_BootstrapPeer.encodingLength(tmp[i])
        length += varint.encodingLength(len)
        length += 1 + len
      }
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.bootstrap)) {
      var tmp = Object.keys(obj.bootstrap)
      for (var i = 0; i < tmp.length; i++) {
        tmp[i] = {key: tmp[i], value: obj.bootstrap[tmp[i]]}
      }
      for (var i = 0; i < tmp.length; i++) {
        if (!defined(tmp[i])) continue
        buf[offset++] = 10
        varint.encode(Map_string_BootstrapPeer.encodingLength(tmp[i]), buf, offset)
        offset += varint.encode.bytes
        Map_string_BootstrapPeer.encode(tmp[i], buf, offset)
        offset += Map_string_BootstrapPeer.encode.bytes
      }
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      bootstrap: {}
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        var tmp = Map_string_BootstrapPeer.decode(buf, offset, offset + len)
        obj.bootstrap[tmp.key] = tmp.value
        offset += Map_string_BootstrapPeer.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineSubscription () {
  Subscription.encodingLength = encodingLength
  Subscription.encode = encode
  Subscription.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.buffer)) {
      var len = encodings.bytes.encodingLength(obj.buffer)
      length += 1 + len
    }
    if (defined(obj.topic)) {
      var len = Topic.encodingLength(obj.topic)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.buffer)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.buffer, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.topic)) {
      buf[offset++] = 18
      varint.encode(Topic.encodingLength(obj.topic), buf, offset)
      offset += varint.encode.bytes
      Topic.encode(obj.topic, buf, offset)
      offset += Topic.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      buffer: null,
      topic: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.buffer = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.topic = Topic.decode(buf, offset, offset + len)
        offset += Topic.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function definePacket () {
  Packet.encodingLength = encodingLength
  Packet.encode = encode
  Packet.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.type)) throw new Error("type is required")
    var len = encodings.enum.encodingLength(obj.type)
    length += 1 + len
    if (defined(obj.payload)) {
      var len = encodings.bytes.encodingLength(obj.payload)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.type)) throw new Error("type is required")
    buf[offset++] = 8
    encodings.enum.encode(obj.type, buf, offset)
    offset += encodings.enum.encode.bytes
    if (defined(obj.payload)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.payload, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      type: 1,
      payload: null
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.type = encodings.enum.decode(buf, offset)
        offset += encodings.enum.decode.bytes
        found0 = true
        break
        case 2:
        obj.payload = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineMap_string_Topic () {
  Map_string_Topic.encodingLength = encodingLength
  Map_string_Topic.encode = encode
  Map_string_Topic.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.key)) throw new Error("key is required")
    var len = encodings.string.encodingLength(obj.key)
    length += 1 + len
    if (defined(obj.value)) {
      var len = Topic.encodingLength(obj.value)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.key)) throw new Error("key is required")
    buf[offset++] = 10
    encodings.string.encode(obj.key, buf, offset)
    offset += encodings.string.encode.bytes
    if (defined(obj.value)) {
      buf[offset++] = 18
      varint.encode(Topic.encodingLength(obj.value), buf, offset)
      offset += varint.encode.bytes
      Topic.encode(obj.value, buf, offset)
      offset += Topic.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      key: "",
      value: null
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.key = encodings.string.decode(buf, offset)
        offset += encodings.string.decode.bytes
        found0 = true
        break
        case 2:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.value = Topic.decode(buf, offset, offset + len)
        offset += Topic.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineMap_string_BootstrapPeer () {
  Map_string_BootstrapPeer.encodingLength = encodingLength
  Map_string_BootstrapPeer.encode = encode
  Map_string_BootstrapPeer.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (!defined(obj.key)) throw new Error("key is required")
    var len = encodings.string.encodingLength(obj.key)
    length += 1 + len
    if (defined(obj.value)) {
      var len = BootstrapPeer.encodingLength(obj.value)
      length += varint.encodingLength(len)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (!defined(obj.key)) throw new Error("key is required")
    buf[offset++] = 10
    encodings.string.encode(obj.key, buf, offset)
    offset += encodings.string.encode.bytes
    if (defined(obj.value)) {
      buf[offset++] = 18
      varint.encode(BootstrapPeer.encodingLength(obj.value), buf, offset)
      offset += varint.encode.bytes
      BootstrapPeer.encode(obj.value, buf, offset)
      offset += BootstrapPeer.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      key: "",
      value: null
    }
    var found0 = false
    while (true) {
      if (end <= offset) {
        if (!found0) throw new Error("Decoded message is not valid")
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.key = encodings.string.decode(buf, offset)
        offset += encodings.string.decode.bytes
        found0 = true
        break
        case 2:
        var len = varint.decode(buf, offset)
        offset += varint.decode.bytes
        obj.value = BootstrapPeer.decode(buf, offset, offset + len)
        offset += BootstrapPeer.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
